### ISSUE TITLE
【周刊】第 46 期：你的苹果M系列芯片电脑跑生信顺利么？

### ISSUE THREAD

**Issue by kkjtmac** [ShixiangWang/weekly#1014]
# 生信爱好者周刊（第 46 期）：你的苹果M系列芯片电脑跑生信顺利么？

这里记录每周值得分享的生信相关内容，周日发布。

本杂志开源（GitHub: [ShixiangWang/weekly](https://github.com/ShixiangWang/weekly)），欢迎提交 issue，投稿或推荐生信相关内容。

[「生信周刊讨论区（语雀）」](https://www.yuque.com/shixiangwang/bioinfo) | [「生信讨论区（Gitter）」](https://gitter.im/ShixiangWang/community)

## 封面图

![M2](https://user-images.githubusercontent.com/45822462/191020172-a0dd8213-323d-4964-b788-7a1e065a0220.jpg)

## 本周话题：你的苹果M系列芯片电脑跑生信顺利么？

- https://github.com/ShixiangWang/weekly/issues/1013

## 生信研究

- https://github.com/ShixiangWang/weekly/issues/868 1
- https://github.com/ShixiangWang/weekly/issues/1005 2
- https://github.com/ShixiangWang/weekly/issues/1004 3

## 博文资讯

- https://github.com/ShixiangWang/weekly/issues/997 4
- https://github.com/ShixiangWang/weekly/issues/874 5
- https://github.com/ShixiangWang/weekly/issues/1007 6
- https://github.com/ShixiangWang/weekly/issues/996 7

## 工具

- https://github.com/ShixiangWang/weekly/issues/823 8
- https://github.com/ShixiangWang/weekly/issues/843 9
- https://github.com/ShixiangWang/weekly/issues/795 10
- https://github.com/ShixiangWang/weekly/issues/716 11

## 资源

- https://github.com/ShixiangWang/weekly/issues/994 12
- https://github.com/ShixiangWang/weekly/issues/737 13
- https://github.com/ShixiangWang/weekly/issues/977 14

## 历史上的本周

- 2021：[第 6 期：你会买“炸场”Macbook Pro搞生信吗？](https://mp.weixin.qq.com/s/NeX9HO8LuIj9FWq7ul2Qxw)

## 贡献者（GitHub ID）

「Openbiox 生信周刊」运维小队：

- `@ShixiangWang`
- `@kkjtmac`
- `@NiEntropy`
- `@He-Kai-fly`
- `@JnanZhang`
- `@Tomcxf`
- `@wangdepin`

## 订阅

这个周刊每周日发布，同步更新在微信公众号「优雅R」（elegant-r）上。

微信搜索“优雅R”或者扫描二维码，即可订阅。

![](https://cdn.nlark.com/yuque/0/2022/png/471931/1648306398708-897e7ad4-6008-40f8-9200-ddee834b09a7.png)

（完）

**Comment by wangdepin** [comment]
5、8、12

**Comment by ShixiangWang** [comment]
2、4、9

**Comment by He-Kai-fly** [comment]
申领3、10

**Comment by He-Kai-fly** [comment]
# 生信研究

## 3、Cell | "千人基因组计划"资源扩展——高覆盖全基因组测序和改进的分析方法发现更多基因变异

![image-20220922090002660](https://kaikaihe.oss-cn-beijing.aliyuncs.com/image/202209220900792.png)

​		近日，来自纽约基因组中心的研究人员与麻省总医院、耶鲁大学和人类基因组结构变异联盟（HGSVC）的合作研究在Cell上发表，**其扩展了1kGP资源，分享了一个包含3202个样本高覆盖率WGS资源，包括602个完整的亲子三人组。**研究团队通过机器学习模型集成了多种分析方法，进行了SNV和INDEL的鉴定，并生成了一组全面的SV数据集。研究团队还与前期数据集进行了比较，**强调了此次变体鉴定方法的高灵敏度和高精度，特别是对罕见SNV、INDEL和不同频率SV的检测**，这些都是以前低覆盖率测序无法实现的。

文章链接：https://www.cell.com/cell/fulltext/S0092-8674(22)00991-6?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS0092867422009916%3Fshowall%3Dtrue

DOI: https://doi.org/10.1016/j.cell.2022.08.004



# 工具

## 10、grafify包 | 一键搞定统计绘图

![image-20220922090246757](https://kaikaihe.oss-cn-beijing.aliyuncs.com/image/202209220902863.png)

​			R-grafify包，其包含了5大类共19种可视化图表，帮助大家更便捷的绘制符合出版要求的可视化图表。5个类别分别为：**Two variables、Three or four variables、Numeric X-Y Plots、Before-after Plots、Data distributions**。

**Comment by NiEntropy** [comment]
申领 1、6、14

**Comment by JnanZhang** [comment]
申领7、11、13

**Comment by ShixiangWang** [comment]
2、`[Cancer Cell 专家论坛 | 肿瘤空间转录组学](https://mp.weixin.qq.com/s/uTxeN5-2yxjWUjiSHrqI0A)`

<img width="612" alt="image" src="https://user-images.githubusercontent.com/25057508/191886452-814dac28-e3f9-4d7d-86f5-1647d84ac155.png">

空间转录组学和其他空间技术使科学家能够解剖肿瘤微环境中不同细胞类型的组织和相互作用。本文请专家讨论了该技术的一些方面，从揭示肿瘤微环境和异质性，到跟踪肿瘤进化，到指导肿瘤治疗，到目前的技术挑战。


- 论文链接：https://www.cell.com/cancer-cell/pdf/S1535-6108(22)00385-3.pdf

4、`[四十年编程感想](https://mp.weixin.qq.com/s/PY6FfxxevyXybqofi9gJfg)`

![image](https://user-images.githubusercontent.com/25057508/191888073-784209fd-306e-4a0b-b5f1-0f0e588a7fb2.png)


本文作者8岁学习编程，今年46岁，写了一大堆自己的感想，其核心要点如下：

- 编程是长期职业：你的目标不必局限在学习什么语言或框架，只要吃透基础知识，你可以学会任何你想要的东西。
- 多尝试不同的事情：1）刚开始不要急于求成；2）需要学习很多不同的东西，你按什么顺序学习它们并不是大问题；3）多学习一些困难的东西，容易发现自己的问题；4）最终需要深入某个领域
- 目标是变得更好：不管使用什么技术，你的目标都应该是动手做出成果，让自己变得更好。
- 继续工作：编程既不是短跑，也不是马拉松，而是日记。在日复一日的累积当中，完成你的事业。

文章链接： https://codefol.io/posts/the-forty-year-programmer/

9、`[ggpie](https://github.com/showteeth/ggpie)`

![image](https://user-images.githubusercontent.com/25057508/191888226-2c475cc6-9a9f-4ffb-b0bc-4e85dac3a77e.png)


ggpie利用ggplot2实现了饼图(2D和3D)、甜甜圈饼图和玫瑰饼图的绘制。

**Comment by JnanZhang** [comment]
### [ManuelHentschel/VSCode-R-Debugger](https://github.com/ManuelHentschel/VSCode-R-Debugger)
![image](https://user-images.githubusercontent.com/108639312/191884613-b66d8610-3ac3-4d39-b263-acc0065c699d.png)
该插件将 R 语言的调试功能添加到 Visual Studio Code，依赖于R 包 vscDebugger 。


### Nat. Com. [Sci.｜使用ActiveSVM在单细胞mRNA-seq数据集中发现最小基因集](https://mp.weixin.qq.com/s/sl49BhheTXpB_8FmmVgcfg)
![image](https://user-images.githubusercontent.com/108639312/191895502-95ea4b81-381e-4464-a7b0-79ad328826e3.png)

美国加利福尼亚州帕萨迪纳加州理工学院生物与生物工程系的Matt Thomson通讯发表在 Nature Computational Science 的研究成果：目前，测序成本是导致单细胞mRNA-seq无法应用于许多生物学和临床分析的主要原因。靶向单细胞mRNA-seq通过分析缩减的基因集来降低测序成本，这些基因集以最少的基因捕获生物信息。为此，作者提出了一种主动学习方法，该方法可以识别数量最少但信息量很大的基因集，从而能够使用少量基因识别单细胞数据中的细胞类型、生理状态和遗传扰动。其中的主动特征选择过程通过使用主动支持向量机 (ActiveSVM) 分类器从单细胞数据中生成最小基因集。经实验证明，ActiveSVM 特征选择识别的基因集在细胞图谱和疾病特征数据集上的细胞类型分类准确率能达到约90%。数量少但信息量大的基因集的发现有助于减少将单细胞 mRNA-seq 应用于临床测试、治疗发现和遗传筛选所需的测量次数。
文章链接：https://doi.org/10.1038/s43588-022-00263-8

### [bradtraversy/design-resources-for-developers](https://github.com/bradtraversy/design-resources-for-developers)
![image](https://user-images.githubusercontent.com/108639312/191885917-e4101c69-c893-4381-972f-770b3b8441fd.png)
设计资源集合，项目包含了图片、网站模版、CSS 框架、UI 等资源。

**Comment by NiEntropy** [comment]
1、[[ActiveSVM｜提取scRNA-seq中的最小基因集](https://www.nature.com/articles/s43588-022-00263-8)](https://www.nature.com/articles/s43588-022-00263-8)

![image.png](https://cdn.nlark.com/yuque/0/2022/png/2626379/1664007415199-7b891e9b-84a5-4a2a-b04f-d1dd7f54aec6.png#clientId=uf788ec8b-4ebc-4&crop=0&crop=0&crop=1&crop=1&from=paste&height=340&id=u9bdcb3c2&margin=%5Bobject%20Object%5D&name=image.png&originHeight=340&originWidth=1186&originalType=binary&ratio=1&rotation=0&showTitle=false&size=75133&status=done&style=none&taskId=u11682a89-bd23-4df4-af17-d07a297c1c4&title=&width=1186)
作者开发了一种特征选择方法ActiveSVM，通过带有支持向量机分类器的主动学习策略来处理顺序特征选择。从大型单细胞 mRNA-seq 数据集中提取高信息量的基因，构建用于细胞分类的最小基因集。该方法可以降低计算和测序成本，为主动采样策略提供依据。

- 论文l链接：https://www.nature.com/articles/s43588-022-00263-8
- 教程：https://pypi.org/project/activeSVC/

6、[[熊说肿瘤｜跨越70年的癌症靶向治疗里程碑](https://mp.weixin.qq.com/s/pB8t4eEuuf6N6Hqe-0s9fQhttps://mp.weixin.qq.com/s/pB8t4eEuuf6N6Hqe-0s9fQ)](https://mp.weixin.qq.com/s/pB8t4eEuuf6N6Hqe-0s9fQhttps://mp.weixin.qq.com/s/pB8t4eEuuf6N6Hqe-0s9fQ)

![](https://cdn.nlark.com/yuque/0/2022/png/2626379/1664008007448-02e3951f-e249-4c2a-9648-f2874b9b9d6c.png#clientId=uf788ec8b-4ebc-4&crop=0&crop=0&crop=1&crop=1&from=paste&id=u41ca6cf0&margin=%5Bobject%20Object%5D&originHeight=5444&originWidth=1080&originalType=url&ratio=1&rotation=0&showTitle=false&status=done&style=none&taskId=u9b0f4506-e608-480b-8413-1f6a19bce21&title=)


14、[[单细胞ATAC-seq系列学习笔记汇总](https://mp.weixin.qq.com/s/ZjkSUdE_hek36OAoY566wA)](https://mp.weixin.qq.com/s/ZjkSUdE_hek36OAoY566wA)

![](https://cdn.nlark.com/yuque/0/2022/png/2626379/1664007983114-cd1c947c-748a-4066-be1c-f3f129a18248.png#clientId=uf788ec8b-4ebc-4&crop=0&crop=0&crop=1&crop=1&from=paste&id=u3c25440f&margin=%5Bobject%20Object%5D&originHeight=797&originWidth=544&originalType=url&ratio=1&rotation=0&showTitle=false&status=done&style=none&taskId=uc03d80bf-151a-48cc-aadd-9a3edfd92ba&title=)
详细的scATAC-seq学习笔记汇总，从原始数据上游处理，数据整合，细胞分群，motif富集分析，轨迹分析等。

**Comment by wangdepin** [comment]
5、[[博文｜生物序列比对的几种应用场景](https://mp.weixin.qq.com/s/Z7FTlsQj6WuZt6kghI_Jlw)]

<img width="851" alt="image" src="https://user-images.githubusercontent.com/38637596/192103064-e56a409e-878f-4cbb-aa5a-0b85d1250513.png">


8、[[R包 ggmsa｜多序列比对和相关数据的可视化探索工具](https://mp.weixin.qq.com/s/ZWh2fJoDCryrRTCucnEioQ)]

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/38637596/192103183-cf81c468-f3dd-457c-9823-20b1935b162c.png">

R 包 ggmsa提供了一套全面的方法用于分析和可视化比对序列。ggmsa 实现了序列标识（Sequence logo）、序列束（Sequence bundle）、堆叠序列可视化法（Stacked sequence alignment visualization）和核苷酸比较图（Nucleotide comparative plots）等可视化方法。通过这些可视化方法，ggmsa 实现了从多个角度准确揭示不同序列特征，从而帮助用户探索和解释序列数据。

12、[[课程资源 ｜ DIY.transcriptomics 数据分析课程](https://diytranscriptomics.com/project/lecture-intro)]

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/38637596/192103892-68a9718c-4094-46fa-a8bf-66f8ecd0d3db.png">

宾夕法尼亚大学的一门生物信息学自学课程，涉及 rna-seq 分析和单细胞转录组分析。网站包括课程 slides、video、以及其他一些免费资源。
