### ISSUE TITLE
【推荐】工具 | bioconductor的docker镜像

### ISSUE THREAD

**Issue by lihaicheng7003** [ShixiangWang/weekly#1279]
> 请勾选下方的分类（在`[ ]`中键入`x`，即`[x]`），另外摘要/简介部分尽量使用中文。推荐前请确定没有重复提交。

### 推荐分类

- [ ] 封面（美图用作封面）
- [ ] 话题 （一个疑问，观点或结论）
- [ ] 生信研究 （生物信息学研究与进展）
- [ ] 博文资讯 （有用或有趣的博文）
- [x] 工具 （工具、平台等）
- [ ] 资源推荐 （数据平台、资源合集等）

### 推荐内容

- 标题：bioconductor的docker镜像
- 摘要/简介：bioconductor提供的docker镜像，可以使用docker管理Rstudio，主要在服务器上使用，感觉很好用。只遇到一个小问题是，这个镜像设置优先使用一个二进制仓库（BIOCONDUCTOR_USE_CONTAINER_REPOSITORY=TRUE），需要关掉，不然安包会很慢（官方介绍这个仓库是为了加速安包，但是国内目前没有这个仓库的镜像）
- 链接：https://hub.docker.com/r/bioconductor/bioconductor_docker

多个内容再添加【推荐内容】

**Comment by ShixiangWang** [comment]
谢谢贡献
