### ISSUE TITLE
【推荐】工具 | mathpix

### ISSUE THREAD

**Issue by yiranzhimo** [ShixiangWang/weekly#1402]
> 请勾选下方的分类（在`[ ]`中键入`x`，即`[x]`），另外摘要/简介部分尽量使用中文。推荐前请确定没有重复提交。

### 推荐分类

- [ ] 封面（美图用作封面）
- [ ] 话题 （一个疑问，观点或结论）
- [ ] 生信研究 （生物信息学研究与进展）
- [ ] 博文资讯 （有用或有趣的博文）
- [x] 工具 （工具、平台等）
- [ ] 资源推荐 （数据平台、资源合集等）

### 推荐内容

- 标题：mathpix 公式识别
- 摘要/简介：对于生物信息学的科研工作人员来说，公式是无可避免的，mathpix 是一款非常好的软件，可以通过 OCR 或者手动书写的方式辅助我们得到需要的数学公式。
- 链接：https://mathpix.com/

多个内容再添加【推荐内容】

**Comment by ShixiangWang** [comment]
@yiranzhimo 谢谢贡献，不过这个之前已经记录过了，下次推荐请看下是否重复提交哈

https://github.com/ShixiangWang/weekly/issues/15
