### ISSUE TITLE
【推荐】一个支持多语言扩展的JS版开源词法分析器

### ISSUE THREAD

**Issue by WGrape** [ShixiangWang/weekly#148]
### 推荐分类

- [ ] 封面
- [ ] 话题
- [ ] 生信动态
- [ ] 文章
- [x] 工具
- [ ] 资源推荐

### 推荐内容

- 标题：一个支持多语言扩展的JS版开源词法分析器
- 摘要/简介：一个基于DFA法的支持多语言扩展的JS版开源词法分析器，代码精简，易于学习和使用。
- 链接：https://github.com/WGrape/lexer

![img](https://user-images.githubusercontent.com/35942268/137584888-28a1ce09-3474-4158-8e6f-ccbdb8614930.gif)

**Comment by ShixiangWang** [comment]
挺有意思的，谢谢推荐

**Comment by WGrape** [comment]
不客气 ~
