### ISSUE TITLE
【周刊】第 72 期 把时间当作朋友

### ISSUE THREAD

**Issue by ShixiangWang** [ShixiangWang/weekly#1488]
# 生信爱好者周刊（第 72 期）：把时间当作朋友

这里记录每周值得分享的生信相关内容，周日发布。

本杂志开源（GitHub: [ShixiangWang/weekly](https://github.com/ShixiangWang/weekly)），欢迎提交 issue，投稿或推荐生信相关内容。

[「生信周刊讨论区」](https://github.com/ShixiangWang/weekly/discussions)

## 封面图

- https://github.com/ShixiangWang/weekly/issues/1475

## 本周话题：把时间当作朋友

- https://github.com/ShixiangWang/weekly/issues/1218

## 生信研究

- https://github.com/ShixiangWang/weekly/issues/1062 1
- https://github.com/ShixiangWang/weekly/issues/896 2
- https://github.com/ShixiangWang/weekly/issues/888 3
- https://github.com/ShixiangWang/weekly/issues/906 4

## 博文资讯

- https://github.com/ShixiangWang/weekly/issues/1483 5
- https://github.com/ShixiangWang/weekly/issues/757 6
- https://github.com/ShixiangWang/weekly/issues/1063 7
- https://github.com/ShixiangWang/weekly/issues/1229 8

## 工具

- https://github.com/ShixiangWang/weekly/issues/743 9
- https://github.com/ShixiangWang/weekly/issues/744 10
- https://github.com/ShixiangWang/weekly/issues/748 11
- https://github.com/ShixiangWang/weekly/issues/755 12
- https://github.com/ShixiangWang/weekly/issues/756 13
- https://github.com/ShixiangWang/weekly/issues/782 14

## 资源

- https://github.com/ShixiangWang/weekly/issues/1482 15
- https://github.com/ShixiangWang/weekly/issues/993 16
- https://github.com/ShixiangWang/weekly/issues/793 17

## 历史上的本周

- 第 31 期：[Openbiox 生物信息学社区 2022 拟开展项目，正式招募 ！](https://mp.weixin.qq.com/s?__biz=MzA5NjAyMzU1OA==&mid=2247490131&idx=1&sn=d72a20ec473e557fd57d758d68253063&chksm=90b73f3aa7c0b62c029e998800df73702243e417202637a3a08632960b4f8e276408310394b6&scene=178&cur_album_id=2042658844287336450#rd)

## 贡献者（GitHub ID）

「Openbiox 生信周刊」运维小队：

- `@ShixiangWang`（王诗翔）
- `@kkjtmac`（阚科佳）
- `@NiEntropy`（赵启祥）
- `@He-Kai-fly`（何凯）
- `@JnanZhang`（张佳楠）
- `@Tomcxf`（陈啸枫）
- `@wangdepin`（王德品）
- `@kongjianyang`（空间阳）

## 订阅

这个周刊每周日发布，同步更新在微信公众号「优雅R」（elegant-r）上。

微信搜索“优雅R”或者扫描二维码，即可订阅。

![](https://cdn.nlark.com/yuque/0/2022/png/471931/1648306398708-897e7ad4-6008-40f8-9200-ddee834b09a7.png)

（完）

**Comment by kkjtmac** [comment]
4、10、15

**Comment by He-Kai-fly** [comment]
> 4、10、15

>>1 、5、16

**Comment by He-Kai-fly** [comment]
> 4、10、15

>1、5、16

**Comment by kkjtmac** [comment]
4、`[Nature Methods | 自由探索4D核组数据——马坚团队发布Nucleome Browser平台](https://mp.weixin.qq.com/s/CJrYxeruRZr92hlIsUkwVw)`

![41592_2022_1559_Fig1_HTML](https://user-images.githubusercontent.com/45822462/230411263-e3cdface-d8d1-488b-8bee-a77544d40403.png)

由美国卡内基梅隆大学计算机科学学院马坚团队开发的Nucleome Browser是一由多个Web组件构成，用户根据其需求对其数据进行可视化操作的平台。通过该平台，用户可以充分利用不同类型的4D核组数据和不同的3D表观基因组学数据集，是为最终确定基因组结构和染色质构象如何调节健康和疾病中的基因组功能提供有力的工具。

- 论文链接：https://www.nature.com/articles/s41592-022-01559-3

10、`[基于空间和单细胞转录组学数据的转录分布预测和细胞类型解析整合方法的评测](https://github.com/QuKunLab/SpatialBenchmarking)`

![168304254-1ce93601-9fb5-4546-b2d5-1dc79d890f08](https://user-images.githubusercontent.com/45822462/230411401-207882c6-e350-49ba-a0c9-f235feade958.jpg)

- 工具链接：https://github.com/QuKunLab/SpatialBenchmarking

15、`[免费好用的ChatGPT镜像站点](https://github.com/xx025/carrot)`

本资源整理了70多个好用的ChatGPT镜像站点，在近日大规模封号情况下大家可以尝试一下。
- 资源链接：https://github.com/xx025/carrot

**Comment by NiEntropy** [comment]
> > 4、10、15
> > > 1、5、16
> 
> 3、7、12

8、13、17

**Comment by NiEntropy** [comment]
8、**[[Visual Studio Code 引入 “远程隧道” 功能](https://mp.weixin.qq.com/s/30F0HiimbzI2RYExCdtNRQ)](https://mp.weixin.qq.com/s/30F0HiimbzI2RYExCdtNRQ)**

![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/d5c9390c-c42e-44ce-a3c3-e48fb6cfed1b/Untitled.png)

 **“远程隧道” 功能** 是 VS Code 1.74 版本的一个主要特性，它可以让用户通过远程隧道功能，从任何设备、任何地方安全地访问自己的机器和 VS 代码。远程隧道功能可以让用户在不需要 SSH 的情况下，通过 vscode.dev 或 VS Code 桌面客户端，创建一个到任何机器的连接，例如远程桌面、虚拟机或 WSL 发行版。

用户可以通过三种方式启用远程隧道访问功能：

1. 从帐户菜单或命令面板中选择打开远程隧道访问，这需要在远程计算机上安装 VS Code，并使用 GitHub 账户登录。
2. 从安装了 VS Code 并位于 PATH 上的计算机运行 code tunnel 命令，这可以是远程桌面、虚拟机或 WSL 发行版。这个命令会下载并启动 VS Code 服务器，并创建一个到它的隧道。
3. 下载新的 VS Code CLI，并运行 ./code tunnel 命令，这适用于无法在远程计算机上安装 VS Code 的情况，例如锁定的机器或 VM。
- 官方文档：https://code.visualstudio.com/blogs/2022/12/07/remote-even-better

13、**[[MuSiCal | 突变特征分析工具](https://github.com/parklab/MuSiCal)](https://github.com/parklab/MuSiCal)**

![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/d14d49a2-29f0-4f71-bf12-56855d82a45b/Untitled.png)

MuSiCal 一款基于Python 3.7环境下的突变特征分析工具。作者提供了Jupyter Notebook 示例脚本，赶快去体验一下MuSiCal 的功能。

- github：https://github.com/parklab/MuSiCal
- example scripts：https://github.com/parklab/MuSiCal/blob/main/examples

17、**[[icons | 网络图标库](https://github.com/mitchelloharawild/icons)](https://github.com/mitchelloharawild/icons)**

![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/7ebacf4c-7ace-4c4c-8efd-0496edf2122a/Untitled.png)

icons包可以让用户在报告、演示和应用中轻松地添加网络图标。它集成了许多来自网络的流行图标库。比如：Font Awesome 、Academicons、Simple Icons、Google’s Material Design、Octicons、Feather Icons、**Bioicons** 等。

- github：https://github.com/mitchelloharawild/icons

**Comment by He-Kai-fly** [comment]
## 1、[Science最新：Jeff Gore团队揭示复杂生态系统中涌现的相变 (qq.com)](https://mp.weixin.qq.com/s/UJ6F7UqHUMo1Bz4goLb5tw)

![image-20230404112721514](https://kaikaihe.oss-cn-beijing.aliyuncs.com/image/202304041127886.png)

> 生态学致力于理解自然生态系统中的多样化的物种和复杂的动力学行为，然而科学家长期缺乏描述和预测生物多样性和生态动力学的统一框架。MIT物理系的胡脊梁和Jeff Gore等科学家结合理论和微生物群落实验，证明只需要掌握少量群落尺度的控制变量，就可以预测复杂生态系统的行为。热力学描述大量气体分子的行为只需要温度和压强等少数涌现的状态变量，而不需要知道每个分子的坐标和速度。Jeff Gore等人在生态网络中发现了类似的粗粒化描述方法，他们的实验和理论结果表明，只需要知道物种数量和平均种间相互作用强度这两个粗粒化参数，就可以预测生态群落中涌现的动力学行为以及相变。物种数量和平均种间相互作用的增加会导致群落在三个涌现的动力学相之间发生相变，从所有物种稳定共存相，转变到部分物种稳定共存相，最终转变到物种数量随时间持续振荡相。他们还发现高物种多样性和群落持续震荡之间存在正反馈。相关成果10月6日发表于***Science***杂志最新一期。

- 论文链接：https://www.science.org/doi/10.1126/science.abm7841
- 官方报道：https://www.science.org/content/article/powerful-physics-tool-could-help-scientists-understand-complex-ecosystems



## 5、[国家癌症中心：2023年最新发布全国各省癌症高发地图 (qq.com)](https://mp.weixin.qq.com/s/8VVrJgKKdi2z_TR7dInUIg)

![image-20230404112955770](https://kaikaihe.oss-cn-beijing.aliyuncs.com/image/202304041129918.png)

> 3月22日，《中华肿瘤杂志》发表国家癌症中心、中国医学科学院肿瘤医院的重磅文章，公布2016年中国恶性肿瘤流行数据，首次提供各省主要癌谱流行情况。
>
> 这份报告根据全国各肿瘤登记处上报至全国肿瘤登记中心的2016年恶性肿瘤登记数据，估计2016年中国恶性肿瘤流行特征。纳入符合数据质控标准的487个登记处数据。按性别、城乡、年龄分层计算不同肿瘤的发病率和死亡率。结合中国人口数据，估计2016年中国恶性肿瘤发病、死亡情况。
>
> 结果显示：中国当前的主要恶性肿瘤包括肺癌、结直肠癌、胃癌、肝癌、女性乳腺癌等，前5位恶性肿瘤发病约占全部新发病例的57.27%。**肺癌、肝癌、胃癌、结直肠癌、食管癌是主要的肿瘤死因**，约占全部肿瘤死亡病例的69.25%。





## 16、[6 个机器学习可解释性框架！ (qq.com)](https://mp.weixin.qq.com/s/R1ke2YGK675vd7_UlsyuNw)

![image-20230404113427221](https://kaikaihe.oss-cn-beijing.aliyuncs.com/image/202304041134339.png)



> 随着人工智能的发展为了解决具有挑战性的问题，人们创造了更复杂、更不透明的模型。AI就像一个黑匣子，能自己做出决定，但是人们并不清楚其中缘由。
>
> 建立一个AI模型，输入数据，然后再输出结果，但有一个问题就是我们不能解释AI为何会得出这样的结论。需要了解AI如何得出某个结论背后的原因，而不是仅仅接受一个在没有上下文或解释的情况下输出的结果。在本文中，将介绍6个用于机器学习可解释性的Python框架。

**Comment by ShixiangWang** [comment]
谢谢大家
