### ISSUE TITLE
【周刊】第 76 期:人生是一个长板问题

### ISSUE THREAD

**Issue by kkjtmac** [ShixiangWang/weekly#1581]
# 生信爱好者周刊（第 76 期）：

这里记录每周值得分享的生信相关内容，周日发布。

本杂志开源（GitHub: [ShixiangWang/weekly](https://github.com/ShixiangWang/weekly)），欢迎提交 issue，投稿或推荐生信相关内容。

[「生信周刊讨论区」](https://github.com/ShixiangWang/weekly/discussions)

## 封面图
![image](https://github.com/ShixiangWang/weekly/assets/45822462/75b9c7da-76d7-4c43-9346-1611ac642159)
被海浪扔回陆地的加菲猫
图源：BBC Future-Richard Fisher

## 本周话题：人生是一个长板问题
来自科技爱好者周刊的话题：除了著名的“水桶原理”-水桶的容量由最短的那块木板决定。“长板问题”也应该得到关注，它是指问题的关键不在于最弱点，而在于最强点。 只要有一个点特别出色，这件事情就成功了，其他点的好坏无所谓。

## 生信研究
- https://github.com/ShixiangWang/weekly/issues/1573 1
- https://github.com/ShixiangWang/weekly/issues/1562 2
- https://github.com/ShixiangWang/weekly/issues/1563 3
## 博文资讯
- https://github.com/ShixiangWang/weekly/issues/1557 4
- https://github.com/ShixiangWang/weekly/issues/1197 5
- https://github.com/ShixiangWang/weekly/issues/1259 6
- https://github.com/ShixiangWang/weekly/issues/1561 7
## 工具
- https://github.com/ShixiangWang/weekly/issues/1277 8
- https://github.com/ShixiangWang/weekly/issues/1539 9
- https://github.com/ShixiangWang/weekly/issues/1504 10
## 资源
- https://github.com/ShixiangWang/weekly/issues/1545 11
- https://github.com/ShixiangWang/weekly/issues/1528 12
- https://github.com/ShixiangWang/weekly/issues/1533 13

## 历史上的本周
第35期：[生物信息行业的经济生态](https://mp.weixin.qq.com/s/WdRtpAKrQ15sAx_b-o_Wnw)

## 贡献者（GitHub ID）

「Openbiox 生信周刊」运维小队：

- `@ShixiangWang`（王诗翔）
- `@kkjtmac`（阚科佳）
- `@NiEntropy`（赵启祥）
- `@He-Kai-fly`（何凯）
- `@JnanZhang`（张佳楠）
- `@Tomcxf`（陈啸枫）
- `@wangdepin`（王德品）
- `@kongjianyang`（空间阳）

## 订阅

这个周刊每周日发布，同步更新在微信公众号「优雅R」（elegant-r）上。

微信搜索“优雅R”或者扫描二维码，即可订阅。

![](https://cdn.nlark.com/yuque/0/2022/png/471931/1648306398708-897e7ad4-6008-40f8-9200-ddee834b09a7.png)

（完）

**Comment by ShixiangWang** [comment]
1、9、11

**Comment by JnanZhang** [comment]
> > 1、9、11
> 
> 3、7、13

2、6、12

**Comment by JnanZhang** [comment]
2、`[PNAS | 同时检测同一DNA分子的遗传和表观遗传特征的新方法——MethylSaferSeqS](https://mp.weixin.qq.com/s/bPMddTAdam1MPiDlO-T-JQ)`
![image](https://github.com/ShixiangWang/weekly/assets/108639312/91217971-57fd-417e-a6f4-038f59bd089f)
美国约翰霍普金斯大学医学院的研究团队报道了一种名为“MethylSaferSeqS”的方法。在样本量有限的情况下，该方法能够检测同一DNA模板分子中的遗传和表观遗传变化，且适用于不同大规模平行测序的标准文库制备。经验证，MethylSaferSeqS具有检测癌症患者和健康个体cfDNA中预期突变、甲基化和拷贝数变化的能力。

2、`[重新认识中性粒细胞](https://mp.weixin.qq.com/s/mHWYZ8QHxwr8_2IAR7qXfw)`

![image](https://github.com/ShixiangWang/weekly/assets/108639312/609fc74d-232f-4c99-9c44-08e9f5d585f5)
最近发现的许多“新”中性粒细胞( Neutrophils)功能令人兴奋不已。人们逐渐认识到中性粒细胞具有比抗菌反应更多的功能，并且在不同的组织和病理条件下具有不同表型，这表明中性粒细胞确实有未被刻画的异质性。然而，在大多数已发表的文章中，证据往往是间接的，我们需要可靠的实验证明所描述的细胞实际上是新的中性粒细胞亚群。


12、`[Building reproducible analytical pipelines with R](https://raps-with-r.dev/)`
![image](https://github.com/ShixiangWang/weekly/assets/108639312/8ae984e1-dca2-49f6-8862-d74d9a2d0451)
本书的目的是教你如何使用软件工程和DevOps中的一些最佳实践来使你的项目稳健、可靠和可重现。无论您是独自工作，在小团队还是大团队中工作都无关紧要。无论你的工作是否经过（同行）评审或审计并不重要：本书中介绍的技术将使您的项目更加可靠，并为您节省很多挫败感！

**Comment by NiEntropy** [comment]
> > > 1、9、11
> > 
> > 
> > 3、7、13
> 
> 2、6、12

5、8、10

**Comment by NiEntropy** [comment]
5、[[Linux 系统性能监控工具](https://mp.weixin.qq.com/s/lyMtYPmevR6u7r31UoMWOA)](https://mp.weixin.qq.com/s/lyMtYPmevR6u7r31UoMWOA)

![image](https://github.com/ShixiangWang/weekly/assets/97931116/87835afc-3df3-4f39-b582-c1d3d4c422fd)

top命令是Linux系统自带的系统资源监视工具，除此还有简洁功能强大的类似工具htop、atop、vtop、btop++、Glances、nmon。该推文精简地介绍这些工具的特点和安装方法。

8、**[[RTutor.ai | 让AI帮你处理数据](https://github.com/gexijin/RTutor)](https://github.com/gexijin/RTutor)**

![image](https://github.com/ShixiangWang/weekly/assets/97931116/d5a007f8-b6e1-4825-8f05-1a6eb60e90f4)

RTutor 是一款基于 chatGPT的API的开发的工具，可以快速生成和测试 R 代码。RTutor 将自然语言翻译成 R 脚本，然后在 Shiny 平台内执行。你可以上传一个数据集，然后用英语提出问题或者请求分析，RTutor.ai会自动生成和测试R代码。需要chatGPT的API。

- github：https://github.com/gexijin/RTutor

10、**[XClone |** 单细胞克隆拷贝数变异推断](https://github.com/single-cell-genetics/XClone)

![image](https://github.com/ShixiangWang/weekly/assets/97931116/15927ab5-cc58-41d1-803c-8dfeb3a5b671)

XClone是基于Python开发的一种算法，可以从低覆盖度和稀疏的单细胞RNA测序数据（例如，由10x Genomics，Smart-seq等生成的数据）中推断细胞中的等位基因和单倍型特异性拷贝数。

- github：[https://github.com/single-cell-genetics/XClone](https://github.com/single-cell-genetics/XClone)

**Comment by ShixiangWang** [comment]
1、`[Nature | 首个人类泛基因组草图公布](https://mp.weixin.qq.com/s/S8fHZt_0tcntFSPA3bpt1Q)`

![image](https://github.com/ShixiangWang/weekly/assets/25057508/681a2673-a450-4423-b19e-e504c463d1d4)

人类泛基因组参考联盟（Human Pangenome Reference Consortium）提出了首个人类泛基因组参考草图以及两个使用这一参考为基础进行新遗传学研究的发现。此次公布的泛基因组草图，源自47名祖先不同个体的阵列，为当下的参考人类基因组（GRCh38）添加了1.19亿碱基对和1115个基因重复（一个DNA区域里含有一个基因重复的变异）。


- 论文链接：https://www.nature.com/articles/s41586-023-05896-x

9、`[Word GPT Plus](https://github.com/Kuingsmile/word-GPT-Plus/blob/master/README_cn.md)`

![image](https://github.com/ShixiangWang/weekly/assets/25057508/83b774e5-c803-40bb-b150-1a8d107c4331)

Word GPT Plus 是一个集成了 chatGPT 模型的 Word 插件。它允许你基于你在文档中写的内容生成文本。你可以使用它来翻译、总结、润色或者从零开始写一篇文章。

11、`[MetaSRA ｜ SRA的标准化元数据](https://mp.weixin.qq.com/s/EOx6bojULKMBw1vBttlNCw)`

MetaSRA 是一个规范化管理SRA人类特定样本元数据的数据库，受启发并遵循于ENCODE项目元数据管理的模式。该模式包括将样本映射到生物医学本体中的术语，用样本类型类别标记每个样本，并提取实值属性。我们通过一套新的pipeline实现了这些任务的计算自动化。

<img width="1158" alt="image" src="https://github.com/ShixiangWang/weekly/assets/25057508/690d9894-da7f-41b0-b186-cb5d4fcec519">


- 网站链接：https://metasra.biostat.wisc.edu/

**Comment by kkjtmac** [comment]
Thanks all!
