### ISSUE TITLE
【周刊】第 78 期：霸凌是平庸科学家登上顶峰的手段

### ISSUE THREAD

**Issue by kongjianyang** [ShixiangWang/weekly#1627]
# 生信爱好者周刊（第 78 期）：霸凌是平庸科学家登上顶峰的手段

这里记录每周值得分享的生信相关内容，周日发布。

本杂志开源（GitHub: [openbiox/weekly](https://github.com/openbiox/weekly)），欢迎提交 issue，投稿或推荐生信相关内容。

[「生信周刊讨论区」](https://github.com/openbiox/weekly/discussions)

## 本周话题：

- #1526 

## 生信研究

- #983 1 
- #980 2
- #1010 3

## 博文资讯

- #1055 4
- #1164 5
- #1248 6

## 工具

- #1501 7
- #1476 8
- #864 9

## 资源

- #1194 10
- #1461 11
- #1523 12

## 历史上的本周

[生信爱好者周刊（第 38 期）：选人不选项目的「基石项目」能否走向成功？](https://openbiox.github.io/weekly/issue-38/)

## 贡献者（GitHub ID）

「Openbiox 生信周刊」运维小队：

- `@ShixiangWang`（王诗翔）
- `@kkjtmac`（阚科佳）
- `@NiEntropy`（赵启祥）
- `@He-Kai-fly`（何凯）
- `@JnanZhang`（张佳楠）
- `@Tomcxf`（陈啸枫）
- `@wangdepin`（王德品）
- `@kongjianyang`（空间阳）

## 订阅

这个周刊每周日发布，同步更新在微信公众号「优雅R」（elegant-r）上。

微信搜索“优雅R”或者扫描二维码，即可订阅。

![](https://cdn.nlark.com/yuque/0/2022/png/471931/1648306398708-897e7ad4-6008-40f8-9200-ddee834b09a7.png)

（完）

**Comment by ShixiangWang** [comment]
> 1、5、6

4、9

**Comment by He-Kai-fly** [comment]
> > 1、5、6
> 
> 4、9

> 2、10

**Comment by He-Kai-fly** [comment]
## 2、[Science封面！华大构建全球首个脑再生时空图谱 ](https://mp.weixin.qq.com/s/2nc81ul7Q1oCJUGbHPnqOg)

![image-20230601170321826](https://kaikaihe.oss-cn-beijing.aliyuncs.com/image/202306011704621.png)

> 2022年9月2日，由杭州华大生命科学研究院主导，联合来自3个国家的17个单位的科学家共同组成的研究团队分析比较了蝾螈脑发育和再生过程，**构建了首个蝾螈脑再生时空图谱，这也是全球首个脑再生时空图谱, **相关成果以背靠背封面文章的形式发表于国际顶级学术期刊《科学》。科学家找到了蝾螈脑再生过程中的关键神经干细胞亚群，描绘了此类干细胞亚群重构损伤神经元的过程，同时还发现脑再生与发育过程具有一定的相似性，为认知脑结构和发育过程提供助力，为神经系统的再生医学研究和治疗提供新的方向。

- 论文链接：https://www.science.org/doi/10.1126/science.abp9444

  

## 10、[适合撰写课程论文的 LaTeX 模板](https://mp.weixin.qq.com/s/4dM55x8Vt_4zUIk61rWJgg)

![image-20230601170547574](https://kaikaihe.oss-cn-beijing.aliyuncs.com/image/202306011705663.png)

本文推荐了几个适合写书和笔记的LaTeX模板：

- Elegant LaTeX: https://github.com/ElegantLaTeX
- ElegantPaper: *https://github.com/ElegantLaTeX/ElegantPaper*
- ElegantBook: *https://github.com/ElegantLaTeX/ElegantBook*
- ElegantNote: *https://github.com/ElegantLaTeX/ElegantNote*

**Comment by ShixiangWang** [comment]
4、`[jjVolcano | 一行代码绘制单细胞火山图](https://mp.weixin.qq.com/s/b3NAQUcRJYUZiSoDGqQmPg)`

![image](https://github.com/openbiox/weekly/assets/25057508/e1c0470e-42c1-401d-b2c1-4baa28c015ea)

本文介绍如何使用 scRNAtoolVis 包中的 jjVolcano 函数进行多组火山图的绘制。

9、`[tidyclust ｜ 聚类模型的 tidy 通用接口](https://github.com/tidymodels/tidyclust)`

![image](https://github.com/openbiox/weekly/assets/25057508/f7dc73a0-1187-4b02-b767-5df8959768be)
