### ISSUE TITLE
【推荐】datar: dplyr in python

### ISSUE THREAD

**Issue by pwwang** [ShixiangWang/weekly#23]
### 推荐分类

- [ ] 封面
- [ ] 话题
- [ ] 生信动态
- [ ] 文章
- [x] 工具
- [ ] 资源推荐

### 推荐内容

- 标题：datar: python中的dplyr
- 摘要/简介：
  在生信分析中，`R`是很常用的语言，`R`中数据处理的包，特别是`tidyverse`开发的包，包括dplyr, tidyr, forcats等，很受欢迎。他们的API设计简单易记，配合`ggplot`，简直数据分析+作图的神组合。而`python`中，`pandas`虽然强大，但API繁多且不容易记住。`datar`将`R`中相关的包在`python`中进行了实现，使得`python`中的数据分析也可以用上`dplyr`的语法。`datar`不仅实现了管道操作，并且尽量遵循原包的API设计，对R熟悉的同学很容易上手。
- 链接：https://github.com/pwwang/datar

**Comment by ShixiangWang** [comment]
Wow! 很棒的工具，这个是需要R包支持，还是完全在Python中实现的呢？

**Comment by ShixiangWang** [comment]
logo

![image](https://user-images.githubusercontent.com/25057508/133710223-d00166c2-e19d-4881-b36e-7bf6c5526671.png)

示例：

```python
from datar import f
from datar.dplyr import mutate, filter, if_else
from datar.tibble import tibble
# or
# from datar.all import f, mutate, filter, if_else, tibble

df = tibble(
    x=range(4),
    y=['zero', 'one', 'two', 'three']
)
df >> mutate(z=f.x)
"""# output
        x        y       z
  <int64> <object> <int64>
0       0     zero       0
1       1      one       1
2       2      two       2
3       3    three       3
"""

df >> mutate(z=if_else(f.x>1, 1, 0))
"""# output:
        x        y       z
  <int64> <object> <int64>
0       0     zero       0
1       1      one       0
2       2      two       1
3       3    three       1
"""

df >> filter(f.x>1)
"""# output:
        x        y
  <int64> <object>
0       2      two
1       3    three
"""

df >> mutate(z=if_else(f.x>1, 1, 0)) >> filter(f.z==1)
"""# output:
        x        y       z
  <int64> <object> <int64>
0       2      two       1
1       3    three       1
"""

```

**Comment by pwwang** [comment]
> Wow! 很棒的工具，这个是需要R包支持，还是完全在Python中实现的呢？

Purely in python, backended by pandas. No `R` at all.

**Comment by ShixiangWang** [comment]
这就厉害了。我看到example中的`f`似乎指代 tidyverse中的`.data`。这个在README中建议说明下指代管道上游结果数据框，不然对一些初学者会有理解困难。

感谢分享。

**Comment by pwwang** [comment]
`f`不完全指代上文的data，所以没有单独在README中提，这里有详细的文档：
https://pwwang.github.io/datar/f/

**Comment by ShixiangWang** [comment]
好的，将在第二期进行推荐。

谢谢。

该issue将关闭。
