### ISSUE TITLE
[Suggestion] Use github "release" to publish each issue (每一期)

### ISSUE THREAD

**Issue by pwwang** [ShixiangWang/weekly#28]
Some people, like me, are used to `watch` some repos, but just `Releases` rather than `All activities`. Watching `All activities` of a repo can get very annoying, but watching `releases` would be fine since people don't care how you work out the release but just the release itself.

By doing so, this repo can also gain an increasing "number of watching" (upper right corner, on the left of "Stars").

**Comment by ShixiangWang** [comment]
Thanks, I will include all contents from issue-2 in release https://github.com/ShixiangWang/weekly/releases
