### ISSUE TITLE
【推荐】一个超有意思的周刊

### ISSUE THREAD

**Issue by mugpeng** [ShixiangWang/weekly#324]
### 推荐分类

- [ ] 封面
- [ ] 话题
- [ ] 生信动态
- [ ] 文章
- [ ] 工具
- [x] 资源推荐
``
### 推荐内容

- 标题：[互联网游荡杂志](https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzU5ODc3OTA0NQ==&action=getalbum&album_id=2061901943265951744&scene=173&from_msgid=2247487348&from_itemidx=1&count=3&nolastread=1#wechat_redirect)
- 摘要/简介：毛遂自荐😄，我自己正在每周更新的杂志。
这里记录一段时间我在互联网上看到的有意思的内容与信息，防止它们在我的脑袋里走丢了。
![image](https://user-images.githubusercontent.com/52995448/145325440-cb70ac56-f7e5-470b-ac89-38ccd55832b6.png)

**Comment by ShixiangWang** [comment]
Thanks
