### ISSUE TITLE
【推荐】工具/R包

### ISSUE THREAD

**Issue by mugpeng** [ShixiangWang/weekly#43]
### 推荐分类

- [ ] 封面
- [ ] 话题
- [ ] 生信动态
- [ ] 文章
- [x] 工具
- [ ] 资源推荐

### 推荐内容

- 标题：可视化的内卷
- 摘要/简介：一种增加图像信息密度而不失优雅的极佳策略。
- 链接：https://jokergoo.github.io/spiralize_vignettes/examples.html

多个内容再添加【推荐内容】

**Comment by ShixiangWang** [comment]
谢谢分享
