### ISSUE TITLE
【推荐】资源推荐 | https://github.com/grimmlab/BookChapter-RNA-Seq-Analyses

### ISSUE THREAD

**Issue by ShixiangWang** [ShixiangWang/weekly#481]
### 推荐分类

- [ ] 封面
- [ ] 话题
- [ ] 生信动态
- [ ] 文章
- [ ] 工具
- [x] 资源推荐

### 推荐内容

- 标题：
- 摘要/简介：
- 链接：https://github.com/grimmlab/BookChapter-RNA-Seq-Analyses

多个内容再添加【推荐内容】

**Comment by He-Kai-fly** [comment]
## 博文资讯

[推荐 10 个好用到爆的 Jupyter Notebook 插件 (qq.com)](https://mp.weixin.qq.com/s/TJEuad82ZVzsbh5BGo50sQ)

![image-20220730152036924](https://kaikaihe.oss-cn-beijing.aliyuncs.com/image/202207301520016.png)

​		Jupter Notebook 是基于网页的用于交互计算的应用程序，可以在网页中直接编写和运行代码，具有灵活、高度可扩展的特性，用户可通过安装插件轻松实现一些实用的功能，而本文介绍几个在**jupyter notebook**中被广泛用到的插件，能够更好地帮助大家进行数据分析可视化，大大提高日常的工作效率！！

## 工具

### simpr

![image-20220730153251830](https://kaikaihe.oss-cn-beijing.aliyuncs.com/image/202207301532899.png)

Github: https://github.com/statisfactions/simpr

 		Simpr包提供了一个通用、简单清晰且友好的框架，用于生成模拟数据，拟合模型和整理模型结果，完整的工作流可以在单个pipeline中完成，且不需外部函数的创建以及全局变量和循环的使用，该包功能对一些功率分析、设计分析、仿真研究和教学统计数据十分有用~



## 资源

### Design and Analysis of RNA Sequencing Data

![image-20220730154055386](https://kaikaihe.oss-cn-beijing.aliyuncs.com/image/202207301540452.png)

​		本章内容针对RNASeq数据分析提供了全面的概述，包括质量评估，reads的预处理、reads比对，基因定量、可变剪切和差异分析等内容，另外本书中也提供了带有简要描述的代码和数据格式，该工作流的具体使用步骤，详见Github文档。

Github：https://github.com/grimmlab/BookChapter-RNA-Seq-Analyses

Book：https://doi.org/10.1007/978-3-030-62490-3_11

Amazon link: https://www.amazon.com/Generation-Sequencing-Analysis-Materials-Biosciences/dp/3030624897
