### ISSUE TITLE
【推荐】工具/资源推荐 | Hub Mirror Action

### ISSUE THREAD

**Issue by ShixiangWang** [ShixiangWang/weekly#576]
### 推荐分类

- [ ] 封面
- [ ] 话题
- [ ] 生信动态
- [ ] 文章
- [x] 工具
- [ ] 资源推荐

### 推荐内容

- 标题：
- 摘要/简介：
- 链接：https://github.com/Yikun/hub-mirror-action

多个内容再添加【推荐内容】

**Comment by Yikun** [comment]
@ShixiangWang 哈哈，无意间看到，感谢诗翔！

**Comment by ShixiangWang** [comment]
@Yikun 不客气，好东西值得分享。之前我也写过推文来着
