### ISSUE TITLE
【推荐】toml-bench: 在python中该使用哪个toml包呢？

### ISSUE THREAD

**Issue by pwwang** [ShixiangWang/weekly#679]
### 推荐分类

- [ ] 封面
- [ ] 话题
- [ ] 生信动态
- [ ] 文章
- [x] 工具
- [ ] 资源推荐

### 推荐内容

- 标题：https://github.com/ruanyf/weekly/issues/2392
- 摘要/简介：
  - 项目描述：
    这个项目对python中不同toml包进行了测试，让人更全面的了解不同的toml包的优缺点。让人很容易选择适当自己项目的toml包。也让toml包开发者有了一套基准测试，让他们对自己的包的优缺点了如指掌并在后续进行针对性改进。

  - 推荐理由：
    在开发python项目涉及使用toml配置文件的时候总是不知道该使用哪个toml包。这个项目从各个方面对python中的toml包进行了测试，让人更容易做出选择。
- 链接：

  https://github.com/pwwang/toml-bench

**Comment by ShixiangWang** [comment]
Thanks
