### ISSUE TITLE
【推荐】工具/资源推荐 | https://nav.ops-coffee.cn/weekly.html

### ISSUE THREAD

**Issue by ops-coffee** [ShixiangWang/weekly#694]
### 推荐分类

- [ ] 封面
- [ ] 话题
- [ ] 生信动态
- [ ] 文章
- [x] 工具
- [ ] 资源推荐

### 推荐内容

- 标题：
- 摘要/简介：偶然看到周刊很不错，收录到了周刊导航，希望能有所帮助
- 链接：https://nav.ops-coffee.cn/weekly.html

多个内容再添加【推荐内容】

**Comment by ShixiangWang** [comment]
@ops-coffee 谢谢~
