### ISSUE TITLE
【推荐】工具/资源推荐 | Scissor

### ISSUE THREAD

**Issue by PiaoyangGuohai1** [ShixiangWang/weekly#742]
### 推荐分类

- [ ] 封面
- [ ] 话题
- [ ] 生信动态
- [ ] 文章
- [x] 工具
- [ ] 资源推荐

### 推荐内容

- 标题：Scissor: Single-Cell Identification of Subpopulations with bulk Sample phenOtype coRrelation
- 摘要/简介：
- 链接：https://github.com/sunduanchen/Scissor

多个内容再添加【推荐内容】

**Comment by ShixiangWang** [comment]
谢谢 #314 已经以paper的形式推过，这样后面可以以工具的形式再分享下。
