### ISSUE TITLE
【推荐】文章/资源推荐 

### ISSUE THREAD

**Issue by mugpeng** [ShixiangWang/weekly#770]
> 请勾选下方的分类（在`[ ]`中键入`x`，即`[x]`），另外摘要/简介部分尽量使用中文。

### 推荐分类

- [ ] 封面
- [ ] 话题
- [ ] 生信动态
- [] 文章
- [ ] 工具
- [x] 资源推荐

### 推荐内容

- 标题：医学数据科学课程
- 摘要/简介：非常棒的基于Rmd 的公开课程资料，从推断假设，数据分布，批次处理，以及基因组数据的处理。
- 链接：http://genomicsclass.github.io/book/

多个内容再添加【推荐内容】

### 推荐分类

- [ ] 封面
- [ ] 话题
- [ ] 生信动态
- [x] 文章
- [ ] 工具
- [] 资源推荐

### 推荐内容

- 标题：肿瘤克隆进化之不同进化模式
- 摘要/简介：总结了肿瘤克隆进化的不同模式，以及各个癌种现有进化模式的研究，整个系列都很值得一读。
- 链接：https://mp.weixin.qq.com/s/9ZsHz0SnVE9FabCHBvK5eQ

**Comment by ShixiangWang** [comment]
3q
