### ISSUE TITLE
【推荐】工具 | Proksee

### ISSUE THREAD

**Issue by 15521271731** [ShixiangWang/weekly#776]
> 请勾选下方的分类（在`[ ]`中键入`x`，即`[x]`），另外摘要/简介部分尽量使用中文。推荐前请确定没有重复提交。

### 推荐分类

- [ ] 封面
- [ ] 话题
- [ ] 生信动态
- [ ] 文章
- [x] 工具
- [ ] 资源推荐

### 推荐内容

- 标题：Proksee
- 摘要/简介：可用于宏基因组分箱（binning）后获得的单菌草图的可视化（网页版仅支持fasta格式核酸序列，暂不支持注释后faa或gff3结果的可视化。可选择linux版本，支持conda安装：https://anaconda.org/bioconda/proksee，支持从头组装和注释）
- 链接：https://proksee.ca/

多个内容再添加【推荐内容】

**Comment by ShixiangWang** [comment]
3q
