### ISSUE TITLE
【推荐】文章| 单细胞，甲基化博士论文推荐

### ISSUE THREAD

**Issue by ylchenchen** [ShixiangWang/weekly#777]
> 请勾选下方的分类（在`[ ]`中键入`x`，即`[x]`），另外摘要/简介部分尽量使用中文。推荐前请确定没有重复提交。

### 推荐分类

- [ ] 封面
- [ ] 话题
- [ ] 生信动态
- [x] 文章
- [ ] 工具
- [ ] 资源推荐

### 推荐内容

- 标题：A profile of differential DNA methylation in sporadic human prion disease blood: precedent, implications and clinical promise
- 摘要/简介：2019-伦敦大学博士论文，全方位详细阐述甲基化内容，包含复现代码
- 链接：https://discovery.ucl.ac.uk/id/eprint/10082183/1/THESIS%20%28FINAL%20CORRECTED%20DRAFT%29.pdf

### 推荐内容

- 标题：Unraveling population heterogeneity using single-cell analysis
- 摘要/简介：2022-华盛顿大学博士论文，单细胞分类算法的介绍
- 链接：https://openscholarship.wustl.edu/cgi/viewcontent.cgi?article=3712&context=art_sci_etds

多个内容再添加【推荐内容】

**Comment by ShixiangWang** [comment]
3q
