### ISSUE TITLE
【推荐】话题 | 生物信息行业的经济生态

### ISSUE THREAD

**Issue by qins** [ShixiangWang/weekly#812]
> 请勾选下方的分类（在`[ ]`中键入`x`，即`[x]`），另外摘要/简介部分尽量使用中文。推荐前请确定没有重复提交。

### 推荐分类

- [ ] 封面（美图用作封面）
- [x] 话题 （一个疑问，观点或结论）
- [ ] 生信研究 （生物信息学研究与进展）
- [ ] 博文资讯 （有用或有趣的博文）
- [ ] 工具 （工具、平台等）
- [ ] 资源推荐 （数据平台、资源合集等）

### 推荐内容

- 标题：生物信息行业的经济生态
- 摘要/简介：
  - 任何一个领域或行业要蓬勃发展, 大概率会有需求方(资金来源) -> 整合链接方(分发网络) -> 提供方(实现者), 很多时候链条会重复就像STR
  - 明确和公开了各方角色, 就相当于进入市场经济, 而市场经济更容易规范和刺激领域或行业发展
  - 另外, 生信人也是要恰饭的, 如果搞生信能轻松养家糊口, 相信也会有更多人参与进来
- 链接：好像还没人讨论过生信的经济生态话题, 大家作为老生信人充当这个链接吧, 这个话题主要还是靠大家参与讨论

多个内容再添加【推荐内容】

**Comment by ShixiangWang** [comment]
THanks.
