### ISSUE TITLE
【推荐】工具 | BioWebStack

### ISSUE THREAD

**Issue by shenweiyan** [ShixiangWang/weekly#850]
> 请勾选下方的分类（在`[ ]`中键入`x`，即`[x]`），另外摘要/简介部分尽量使用中文。推荐前请确定没有重复提交。

### 推荐分类

- [ ] 封面（美图用作封面）
- [ ] 话题 （一个疑问，观点或结论）
- [ ] 生信研究 （生物信息学研究与进展）
- [ ] 博文资讯 （有用或有趣的博文）
- [x] 工具 （工具、平台等）
- [ ] 资源推荐 （数据平台、资源合集等）

### 推荐内容

- 标题：将一些重点资源整理成一个生信导航网页
- 摘要/简介：受 [@郑宝童](https://www.yuque.com/btzheng) 和 [@王诗翔](https://github.com/ShixiangWang) 老师的一些文章和讨论影响和启发，基于 [WebStack-Hugo](https://github.com/shenweiyan/webstack-hugo)  主题致力于将一些重点资源整理成一个生信导航网页。
- 链接：https://hao.bioitee.com/

多个内容再添加【推荐内容】

**Comment by ShixiangWang** [comment]
做的很好
